### ISSUE TITLE
Adicionar Política de cache baseada em Nomes

### ISSUE THREAD

**Issue by luizcarlosfaria** [thiagoloureiro/TestaCache#2]
Na última conversa falamos sobre política de cache, e vi que foi implementada a política de cache baseada no tempo, onde você determina durante o build o tempo de vida do cache de determinado método, no entanto falta 1 coisa:

Permitir que você dê nomes como "CacheCurtaduracao", "CacheLongaDuracao", "****" para expressar uma referência a uma configuração. O que isso significa: que os nomes apontam para configurações (veja como estruturar isso) mas que nas configurações estão os devidos valores. Isso faz com que uma mudança na política de cache (tempo) não necessite nem cause rebuild da aplicação. Essa deve ser uma possibilidade, já que estamos falando de algo genérico.

**Comment by thiagoloureiro** [comment]
@luizcarlosfaria pensei em colocar no app.config / web.config uma chave no appsettings

```
<appSettings>
  <add key="CachePolicyShort" value="60" />
  <add key="ChachePolicyMedium" value="600" />
  <add key="CachePolicyLong" value="86400" />
</appSettings>
```
1 minuto / 10 minutos / 1 dia .

podendo ser alterado, é claro.

Se você tiver alguma outra sugestão de lugar para inserir essa configuração fique à vontade.

abs!

**Comment by luizcarlosfaria** [comment]
Boa! Depois pensa em achar algum parser para que pudesse ser escrito em formato mais fluente como:
1s
10m
1h
Seria legal! Mas a ideia é essa mesmo!

**Comment by thiagoloureiro** [comment]
Adicionado para o próximo release
Estou subindo a nova versão com suporte a .Net Core
